@startuml 程序时序图
title 程序时序图

actor 客户端A
actor 客户端B
actor 客户端C
participant 服务端

客户端A -> 服务端: 准备
客户端B -> 服务端: 准备
客户端C -> 服务端: 准备
服务端 -> 客户端A: 发牌
服务端 -> 客户端B: 发牌
服务端 -> 客户端C: 发牌
服务端 -> 客户端A: 确定地主（服务器分配）
服务端 -> 客户端A: 更新手牌

客户端A <- 服务端: 请求出牌
客户端A -> 服务端: 出牌
服务端 -> 客户端A: 判断出牌结果
客户端B <- 服务端: 请求出牌
客户端B -> 服务端: 出牌
服务端 -> 客户端B: 判断出牌结果
客户端C <- 服务端: 请求出牌
客户端C -> 服务端: 出牌
服务端 -> 客户端C: 判断出牌结果
客户端A -> 服务端: 手牌为空
服务端 -> 客户端A: 结束游戏
服务端 -> 客户端B: 结束游戏
服务端 -> 客户端C: 结束游戏
@enduml
